sudo: false
language: node_js
node_js:
  - "6.4"

python:
  - '3.5'

install:
  - npm install

script:
  - npm test

notifications:
  slack:
    secure: eHwEPhBI/9EO97G7yGjuAcutaQrXBcuH8lYj2yeJrfQGviV1rqxvY5L7GGXvEtfrd0mzGkcMLFo99PJpFK+Ct7tbb9hFsabD1+HekYbjwEKTaCBs6p/qbWf9bIU4uNXlDBN9T60Iju5PjuNglAsBa7c9rwofR/djmu2IaLolGhzHBMzGEJt0enCHDR6CoXgFtn5f3xxrnLEsUi+IJyiAmDG1IitHcwErDQZ6WE6LrRBlez3chU8k5YaRJEgGnbUpZ9JWhUeS0cXhEPqPyVNnYZCd0QEV5CTrrYc1LEzRMqVRW5CLGiF70/0I+VBhb0UkWsjo2g6vHZKUGgr/cieMt/k+17M2clkBcjTGJUAWRu0duuTfkefMKaW7lDpki9xChr0ZmdD4hgDi/uYCU+8BupJirxCDy1P4g5CC0wMejhWpADQ1E/j73Y4hg9w4Gu0Cyh6pFA6WNTob+qyOpt9Px5oKgGTuGzEQYoVdicNnFN96FuNec9S2KSLrqZEvFIxCY71AbtRaLfG+hQmTRvB+IsVIYVsR9wt2ilmFQ9xKbCHFfo6QNvAUIzIyfF+6bYr5D3+8m6OrAo54IUY6/iefh+vRaz5QxL3Iy0KG9Gfuibw+H7ZqvOR+B7IOBkjsB/aJSBkCzgOQQ5wzJf4EzW3QleHmPChW/XSGSi5wByGUpzA=
  email: false
