environment:
  nodejs_version: "6.4.0"
  matrix:
    - PYTHON: "C:/Python35"

init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off

notifications:
  - provider: Slack
    incoming_webhook: https://hooks.slack.com/services/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
