environment:
  nodejs_version: "6.4.0"
  matrix:
    - PYTHON: "C:/Python27"
    - PYTHON: "C:/Python35"

init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off
